[package]
name = "hero"
description = "Send GitHub Actions workflow history to OpenTelemetry as spans and traces"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["wrap_help"] }
